-- Create Database
CREATE DATABASE OnlineBookstore;

-- Switch to the database
\c OnlineBookstore;

-- Create Tables
DROP TABLE IF EXISTS Books;
CREATE TABLE Books (
    Book_ID SERIAL PRIMARY KEY,
    Title VARCHAR(100),
    Author VARCHAR(100),
    Genre VARCHAR(50),
    Published_Year INT,
    Price NUMERIC(10, 2),
    Stock INT
);
DROP TABLE IF EXISTS customers;
CREATE TABLE Customers (
    Customer_ID SERIAL PRIMARY KEY,
    Name VARCHAR(100),
    Email VARCHAR(100),
    Phone VARCHAR(15),
    City VARCHAR(50),
    Country VARCHAR(150)
);
DROP TABLE IF EXISTS orders;
CREATE TABLE Orders (
    Order_ID SERIAL PRIMARY KEY,
    Customer_ID INT REFERENCES Customers(Customer_ID),
    Book_ID INT REFERENCES Books(Book_ID),
    Order_Date DATE,
    Quantity INT,
    Total_Amount NUMERIC(10, 2)
);

SELECT * FROM Books;
SELECT * FROM Customers;
SELECT * FROM Orders;


-- Import Data into Books Table
COPY Books(Book_ID, Title, Author, Genre, Published_Year, Price, Stock) 
FROM 'D:\Course Updates\30 Day Series\SQL\CSV\Books.csv' 
CSV HEADER;

-- Import Data into Customers Table
COPY Customers(Customer_ID, Name, Email, Phone, City, Country) 
FROM 'D:\Course Updates\30 Day Series\SQL\CSV\Customers.csv' 
CSV HEADER;

-- Import Data into Orders Table
COPY Orders(Order_ID, Customer_ID, Book_ID, Order_Date, Quantity, Total_Amount) 
FROM 'D:\Course Updates\30 Day Series\SQL\CSV\Orders.csv' 
CSV HEADER;


Beginner-Friendly Questions:

-- 1) Retrieve all books in the "Fiction" genre:


-- 2) Find books published after the year 1950:


-- 3) List all customers from the Canada:


-- 4) Show orders placed in November 2023:


-- 5) Retrieve the total stock of books available:


-- 6) Find the details of the most expensive book:


-- 7) Show all customers who ordered more than 1 quantity of a book:


-- 8) Retrieve all orders where the total amount exceeds $20:


-- 9) List all genres available in the Books table:


-- 10) Find the book with the lowest stock:


-- 11) Calculate the total revenue generated from all orders:



-- Intermediate to Advance Questions : 


-- 1) Retrieve the total number of books sold for each genre:



-- 2) Find the average price of books in the "Fantasy" genre:



-- 3) List customers who have placed at least 2 orders:


-- 4) Find the most frequently ordered book:


-- 5) Show the top 3 most expensive books of 'Fantasy' Genre :



-- 6) Retrieve the total quantity of books sold by each author:


-- 7) List the cities where customers who spent over $30 are located:


-- 8) Find the customer who spent the most on orders:


--9) Calculate the stock remaining after fulfilling all orders:


Advanced Questions:

-- 1) Find the top 5 best-selling books based on total quantity sold.


-- 2) Retrieve authors whose books generated more than $50 in revenue.


-- 3) Calculate total revenue generated by each genre.


-- 4) Find customers who never placed an order.


-- 5) Show books that have never been ordered.


-- 6) Find the average order value for each customer.


-- 7) Retrieve the month-wise revenue generated from orders.


-- 8) Find the author whose books sold the highest quantity.

 
-- 9) Show the customer order count for each city.


-- 10) Find books whose stock is below the average stock level.


-- 11) Retrieve customers who purchased books from more than one genre.


-- 12) Find the highest revenue-generating book.


-- 13) Calculate cumulative sales amount for each customer.


-- 14) Rank books based on total sales revenue.


-- 15) Find the second most expensive book.


-- 16) Identify customers whose spending is above average customer spending.


-- 17) Retrieve the percentage contribution of each genre to total revenue.


-- 18) Find customers who ordered the same book multiple times.


-- 19) Calculate revenue loss due to unsold stock.


-- 20) Find the most popular genre by total books sold.


-- 21) Generate a sales performance report containing Book Title, Author, Total Quantity Sold, Total Revenue, and Remaining Stock.


-- 22) Create a customer segmentation report (High Spender, Medium Spender, Low Spender) based on total spending.


-- 23) Find repeat customers (customers with 3 or more orders).


-- 24) Calculate running total revenue over time.


-- 25) Find the monthly top-selling book.


-- 26) Detect books at risk of stockout (remaining stock less than 5).









