-- ADVANCE QUESTIONS:
-- 1) Find the top 5 best-selling books based on total quantity sold.
SELECT Title, Sum(Quantity) AS Total_Sold
FROM Books
JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Title
ORDER BY Total_Sold DESC
LIMIT 5;


-- 2) Retrieve authors whose books generated more than $50 in revenue.
SELECT Author, SUM(Total_Amount) AS Revenue
FROM Books
JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Author
HAVING Revenue > 50;


-- 3) Calculate total revenue generated by each genre.
SELECT Genre, SUM(Total_Amount) AS Total_Revenue
FROM Books
JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Genre;


-- 4) Find customers who never placed an order.
SELECT Name
FROM Customers
LEFT JOIN Orders
ON Customers.Customer_ID = Orders.Customer_ID
WHERE Order_ID IS NULL;


-- 5) Show books that have never been ordered.
SELECT Title
FROM Books
LEFT JOIN Orders
ON Books.Book_ID = Orders.Book_ID
WHERE Order_ID IS NULL;


-- 6) Find the average order value for each customer.
SELECT Name,
       AVG(Total_Amount) AS Average_Order_Value
FROM Customers
JOIN Orders
ON Customers.Customer_ID = Orders.Customer_ID
GROUP BY Name;


-- 7) Retrieve the month-wise revenue generated from orders.
SELECT MONTH(Order_Date) AS Month,
       SUM(Total_Amount) AS Revenue
FROM Orders
GROUP BY Month
ORDER BY Month;


-- 8) Find the author whose books sold the highest quantity.
SELECT Author,
       SUM(Quantity) AS Total_Sold
FROM Books
JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Author
ORDER BY Total_Sold DESC
LIMIT 1;
 

-- 9) Show the customer order count for each city.
SELECT City,
       COUNT(Order_ID) AS Total_Orders
FROM Customers
JOIN Orders
ON Customers.Customer_ID = Orders.Customer_ID
GROUP BY City;


-- 10) Find books whose stock is below the average stock level.
SELECT Title, Stock
FROM Books
WHERE Stock <
(
    SELECT AVG(Stock)
    FROM Books
);


-- 11) Retrieve customers who purchased books from more than one genre.
SELECT Name,
       COUNT(DISTINCT Genre) AS Genre_Count
FROM Customers
JOIN Orders
ON Customers.Customer_ID = Orders.Customer_ID
JOIN Books
ON Orders.Book_ID = Books.Book_ID
GROUP BY Name
HAVING Genre_Count > 1;


-- 12) Find the highest revenue-generating book.
SELECT Title,
       SUM(Total_Amount) AS Revenue
FROM Books
JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Title
ORDER BY Revenue DESC
LIMIT 1;


-- 13) Calculate cumulative sales amount for each customer.
SELECT Name,
       Order_Date,
       Total_Amount,
       SUM(Total_Amount)
       OVER(
            PARTITION BY Customers.Customer_ID
            ORDER BY Order_Date
           ) AS Cumulative_Sales
FROM Customers
JOIN Orders
ON Customers.Customer_ID = Orders.Customer_ID;


-- 14) Rank books based on total sales revenue.
SELECT Title,
       SUM(Total_Amount) AS Revenue,
       RANK() OVER(
           ORDER BY SUM(Total_Amount) DESC
       ) AS Book_Rank
FROM Books
JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Title;


-- 15) Find the second most expensive book.
SELECT Title, Price
FROM Books
ORDER BY Price DESC
LIMIT 1 OFFSET 1;


-- 16) Identify customers whose spending is above average customer spending.
SELECT Name,
       SUM(Total_Amount) AS Total_Spent
FROM Customers
JOIN Orders
ON Customers.Customer_ID = Orders.Customer_ID
GROUP BY Name
HAVING Total_Spent >
(
    SELECT AVG(Customer_Total)
    FROM
    (
        SELECT SUM(Total_Amount) AS Customer_Total
        FROM Orders
        GROUP BY Customer_ID
    ) AS Avg_Table
);


-- 17) Retrieve the percentage contribution of each genre to total revenue.
SELECT Genre,
       ROUND(
           (SUM(Total_Amount) * 100.0) /
           (SELECT SUM(Total_Amount)
            FROM Orders),
           2
       ) AS Revenue_Percentage
FROM Books
JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Genre;


-- 18) Find customers who ordered the same book multiple times.
SELECT Name,
       Title,
       COUNT(Order_ID) AS Times_Ordered
FROM Customers
JOIN Orders
ON Customers.Customer_ID = Orders.Customer_ID
JOIN Books
ON Orders.Book_ID = Books.Book_ID
GROUP BY Name, Title
HAVING COUNT(Order_ID) > 1;


-- 19) Calculate revenue loss due to unsold stock.
SELECT Title,
       (Stock - IFNULL(SUM(Quantity),0)) * Price
       AS Revenue_Loss
FROM Books
LEFT JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Title, Stock, Price;


-- 20) Find the most popular genre by total books sold.
SELECT Genre,
       SUM(Quantity) AS Total_Sold
FROM Books
JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Genre
ORDER BY Total_Sold DESC
LIMIT 1;


-- 21) Generate a sales performance report containing Book Title, Author, Total Quantity Sold, Total Revenue, and Remaining Stock.
SELECT Title,
       Author,
       SUM(Quantity) AS Total_Quantity_Sold,
       SUM(Total_Amount) AS Total_Revenue,
       Stock - SUM(Quantity) AS Remaining_Stock
FROM Books
JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Title, Author, Stock;


-- 22) Create a customer segmentation report (High Spender, Medium Spender, Low Spender) based on total spending.
SELECT Name,
       SUM(Total_Amount) AS Total_Spent,
       CASE
            WHEN SUM(Total_Amount) >= 100 THEN 'High Spender'
            WHEN SUM(Total_Amount) BETWEEN 50 AND 99 THEN 'Medium Spender'
            ELSE 'Low Spender'
       END AS Customer_Category
FROM Customers
JOIN Orders
ON Customers.Customer_ID = Orders.Customer_ID
GROUP BY Name;


-- 23) Find repeat customers (customers with 3 or more orders).
SELECT Name,
       COUNT(Order_ID) AS Total_Orders
FROM Customers
JOIN Orders
ON Customers.Customer_ID = Orders.Customer_ID
GROUP BY Name
HAVING COUNT(Order_ID) >= 3;


-- 24) Calculate running total revenue over time.
SELECT Order_Date,
       SUM(Total_Amount) AS Daily_Revenue,
       SUM(SUM(Total_Amount))
       OVER(
            ORDER BY Order_Date
           ) AS Running_Total_Revenue
FROM Orders
GROUP BY Order_Date;


-- 25) Find the monthly top-selling book.
SELECT Month,
       Title,
       Total_Sold
FROM
(
     SELECT MONTH(Order_Date) AS Month,
            Title,
            SUM(Quantity) AS Total_Sold,
            ROW_NUMBER() OVER(
                 PARTITION BY MONTH(Order_Date)
                 ORDER BY SUM(Quantity) DESC
            ) AS rn
     FROM Orders
     JOIN Books
     ON Orders.Book_ID = Books.Book_ID
     GROUP BY Month, Title
) AS Ranked_Books
WHERE rn = 1;


-- 26) Detect books at risk of stockout (remaining stock less than 5).
SELECT Title,
       Stock - IFNULL(SUM(Quantity),0) AS Remaining_Stock
FROM Books
LEFT JOIN Orders
ON Books.Book_ID = Orders.Book_ID
GROUP BY Title, Stock
HAVING Remaining_Stock < 5;